out_directory = "/tmp/usbsas-tests"

[[networks]]
description = "Network"
longdescr = "Send files on a remote server"
url = "http://127.0.0.1:8042/api/uploadbundle"

[source_network]
description = "Source Network"
longdescr = "Export files from network"
url = "http://127.0.0.1:8042/api/downloadbundle"

[analyzer]
url = "http://127.0.0.1:8042/api/scanbundle"
referer = "http://127.0.0.1"

[report]
write_dest = true

[[filters]]
contain = ["__macosx"]

[[filters]]
contain = [".ds_store"]

[[filters]]
contain = [".lnk."]

[[filters]]
contain = [".lnk/"]

[[filters]]
end = ".lnk"

[[filters]]
contain = ["autorun.inf"]

[[filters]]
contain = ["thumbs.db"]

[[filters]]
contain = ["desktop.ini"]

[[filters]]
end = "/$recycle.bin"

[[filters]]
contain = ["/$recycle.bin/"]

[[filters]]
end = "/recycler"

[[filters]]
contain = ["/recycler/"]

[[filters]]
end = "/recycled"

[[filters]]
contain = ["/recycled/"]

[[filters]]
contain = ["/."]

[[filters]]
contain = ["ùÑû"]

[[filters]]
contain = ["test"]
end = "√©"
