[package]
name = "hid-user"
version = "0.1.0"
edition = "2021"
links = "X11,Xtst"
license = "GPL-3.0"

[dependencies]
bitfield = "0.14.0"
env_logger = "0.9.3"
log = "0.4.17"
rusb = "0.9.1"
x11 = "2.20.1"
