[package]
name = "usbsas-mass-storage"
version = "0.1.1"
edition = "2021"
license = "GPL-3.0"

[dependencies]
log = "0.4.17"
lru = "0.7.8"
positioned-io = "0.2.2"
positioned-io2 = "0.3.4"
rusb = "0.9.1"
usbsas-comm = { path = "../usbsas-comm" }
usbsas-proto = { path = "../usbsas-proto" }
usbsas-scsi = { path = "../usbsas-scsi" }

[features]
mock = []
