[package]
name = "usbsas-privileges"
version = "0.1.1"
edition = "2021"
license = "GPL-3.0"

[build-dependencies]
cc = "1.0"

[dependencies]
libc = "0.2"
procfs = { version = "0.14", default-features = false }
syscallz = "0.16"
thiserror = "1.0"
