[package]
name = "usbsas-privileges"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[build-dependencies]
cc = "1.0.77"

[dependencies]
libc = "0.2.137"
procfs = { version = "0.14.1", default-features = false }
syscallz = "0.16.2"
thiserror = "1.0.37"
