[package]
name = "usbsas-process"
version = "0.1.2"
edition = "2021"
license = "GPL-3.0"

[dependencies]
libc = "0.2"
log = "0.4"
nix = { version = "0.28", features = ["fs", "process"] }
thiserror = "1.0"
usbsas-comm = { path = "../usbsas-comm" }
usbsas-utils = { path = "../usbsas-utils" }
