[package]
name = "usbsas-process"
version = "0.1.2"
edition = "2021"
license = "GPL-3.0"

[dependencies]
libc = "0.2"
log = "0.4"
nix = "0.27"
thiserror = "1.0"
usbsas-comm = { path = "../usbsas-comm" }
usbsas-utils = { path = "../usbsas-utils" }
