[package]
name = "usbsas-config"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"

[dependencies]
lazy_static = "1.4.0"
log = "0.4.17"
serde = { version = "1.0.140", features = ["derive"] }
toml = "0.5.9"
